config/routes.rb
Brimir::Application.routes.draw do

  resources :replies, only: [ :create, :new, :destroy ]
  post 'replies/:id/approve' => 'replies#approve', as: 'reply_approve'

  devise_for :users
  devise_scope :user do
    post 'login' => 'sessions#create', :as => 'login'
    post 'logout' => 'sessions#destroy', :as => 'logout'
    get 'current_user' => 'sessions#show_current_user', :as => 'show_current_user'
  end

  resources :users, only: [ :edit, :update ]

  resources :tickets, only: [ :index, :show, :update, :create ]
  post 'tickets/:id/approve' => 'tickets#approve', as: 'ticket_approve'
  post 'tickets/:id/delete', :to => 'tickets#delete_ticket', as: 'delete_ticket'
  post 'tickets/:id/flag', :to => 'tickets#flag_ticket'
  post 'tickets/:id/best', :to => 'tickets#best_ticket'
  get 'all_tickets', :to => 'tickets#all'
  
  post 'replies/:id/delete', :to => 'replies#destroy_reply'
  post 'replies/:id/flag', :to => 'replies#flag_reply'

  root :to => 'tickets#index'

  resources :admins, only: [ :index]

  get '/resources' => 'pages#resources'

end

app/models/ticket.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2014 Ivaldi http://ivaldi.nl
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class Ticket < ActiveRecord::Base

  # validates_presence_of :status_id, :user_id

  # belongs_to :user
  belongs_to :status
  # belongs_to :priority
  # belongs_to :assignee, class_name: 'User'

  # has_many :attachments, as: :attachable, dependent: :destroy

  has_many :replies, dependent: :destroy

  scope :filter_by_assignee_id, ->(assignee_id) {
    if !assignee_id.nil?
      if assignee_id.to_i == 0
        where(assignee_id: nil)
      else
        where(assignee_id: assignee_id)
      end
    else
      all
    end
  }

  scope :search, ->(term) {
    if !term.nil?
      term = '%' + term.downcase + '%'
      where('LOWER(subject) LIKE ? OR LOWER(content) LIKE ?',
          term, term)
    end
  }

  def answered?
    replies.any?(&:answer)
  end

  def as_json
    hash = {
      id: id,
      message: message,
      replies: replies.visible,
      status: status.name,
      text_reference: text_reference,
      created_at: created_at,
      updated_at: updated_at
    }
  end
end

app/controllers/tickets_controller.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2014 Ivaldi http://ivaldi.nl
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class TicketsController < ApplicationController
  before_filter :authenticate_user!, except: [ :create ] 

  def show
    @ticket = Ticket.find(params[:id])
    # @agents = User.agents
    @statuses = Status.all
    # @priorities = Priority.all    

    @reply = @ticket.replies.new
    @is_admin ||= current_user.user_role.is_admin?
    @active_status = Status.find_by_id_from_filters(params[:status_id], @is_admin)
   # @reply.to = @ticket.user.email
  end

  def index
    @agents = User.agents
    @is_admin ||= current_user.user_role.is_admin?
    @statuses = if @is_admin
      Status.filters.select { |s| s.name != 'Deleted' }
    else 
      Status.filters.select { |s| s.name == 'Open' || s.name == 'Closed' }
    end

    @priorities = Priority.all

    @active_status = Status.find_by_id_from_filters(params[:status_id], current_user.user_role.is_admin?)
    # @tickets = @active_status
    #   .tickets
    #   .search(params[:q])
    #   .page(params[:page])
    #   .order(:created_at)
    @tickets = @active_status.tickets
    puts @tickets.first.inspect
    respond_to do |format|
      format.html {
        render action: 'index'
      }
      format.json {
        render :json => @tickets.as_json
      }  
    end  
  end

  def all
    @tickets = Ticket.all
    respond_to do |format|
      format.html {
        render action: 'index'
      }
      format.json {
        render :json => @tickets.as_json
      }  
    end      
  end

  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if current_user.user_role.is_admin? && @ticket.update_attributes(params.permit![:ticket])
        format.html {
          redirect_to tickets_path(status_id: Status.find_by_id_from_filters(params[:status_id]).id), notice: 'Question was successfully updated.'
        }
        format.js {
          render notice: 'Question was succesfully updated.'
        }
        format.json {
          head :no_content
        }
      else
        format.html {
          render action: 'edit'
        }
        format.json {
          render json: @ticket.errors, status: :unprocessable_entity
        }
      end
    end
  end

  def approve
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if current_user.user_role.is_admin? && @ticket.update_attributes(status: Status.find_by_name('Open'))
        format.html {
          redirect_to tickets_path(status_id: Status.find_by_id_from_filters(params[:status_id]).id), notice: 'Question was successfully updated.'
        }
        format.js {
          render notice: 'Question was succesfully updated.'
        }
        format.json {
          render json: @ticket.as_json
        }
      else
        format.html {
          render action: 'edit'
        }
        format.json {
          render json: @ticket.errors, status: :unprocessable_entity
        }
      end
    end
  end

  def delete_ticket
    @ticket = Ticket.find(params[:id]).update_attribute(:status, Status.find_by_name('Deleted'))
    respond_to do |format|
      format.json {
        render :json => {}
      }
    end
  end

  def flag_ticket
    @ticket = Ticket.find(params[:id]).update_attribute(:status, Status.find_by_name('Flagged'))
    respond_to do |format|
      format.json {
        render :json => {}
      }
    end
  end

  def best_ticket
    @ticket = Ticket.find(params[:id]).update_attribute(:status, Status.find_by_name('Best'))
    respond_to do |format|
      format.json {
        render :json => {}
      }
    end
  end

  def create

    @ticket = Ticket.create({message: params[:message], status: Status.default.first, text_reference: params[:text_reference]})

    respond_to do |format|
      format.json { render json: @ticket.as_json, status: :created }
    end
  end

  private
    def ticket_params
      params.require(:message).permit!
    end
end

app/views/tickets/_change_assignee_form.html.erb
<div id="change-assignee" class="reveal-modal small" data-reveal>
  <h3>Assign this ticket to...</h3>

  <%= form_for ticket, remote: true, method: :put do |f| %>
    <p>
      <%= f.select :assignee_id, options_from_collection_for_select(@agents, 'id', 'email', ticket.assignee_id), include_blank: 'Nobody' %>
    </p>
    <%= f.submit 'Assign', class: 'button' %>
  <% end %>

  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/tickets/_change_priority_form.html.erb
<div id="change-priority" class="reveal-modal small" data-reveal>
  <h3>Change priority to...</h3>

  <%= form_for ticket, remote: true, method: :put do |f| %>
    <p>
      <%= f.select :priority_id, options_from_collection_for_select(@priorities, 'id', 'name', ticket.priority_id) %>
    </p>
    <%= f.submit 'Change', class: 'button' %>
  <% end %>

  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/tickets/_change_status_form.html.erb
<div id="change-status" class="reveal-modal small" data-reveal>
  <h3>Change status to...</h3>

  <%= form_for ticket, remote: true, method: :put do |f| %>
    <p>
      <%= f.select :status_id, options_from_collection_for_select(@statuses, 'id', 'name', ticket.status_id) %>
    </p>
    <%= f.submit 'Change', class: 'button' %>
  <% end %>

  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/tickets/index.html.erb
<div class="row">

    <div class="questions">

        <h1 class="page-header"><%= @active_status.name %></h1>

        <% @tickets.each do |ticket| %>
          <div class="question">
              <div class="message" data-message-full="">
                <a href="<%= ticket_url(ticket) %>"><%= truncate(ticket[:message], length: 180, separator: ' ') %></a>
                <div class="message-read">&rsaquo;</div>
              </div>
              <div class="extra">
                <div class="date"><%= l ticket.created_at, format: :short %></div>
                <% if current_user.user_role.is_admin? %>
                <div class="actions">
                    <a class="action identify"><span class="glyphicons iphone"></span></a>
                    <%= link_to(ticket_path(ticket, ticket: { status_id: Status.find_by_name('Deleted').id }, status_id: @active_status.id), method: :put, class: 'action') do %>
                      <span class="glyphicons remove_2"></span>
                    <% end %>
                    <%= link_to(ticket_path(ticket, ticket: { status_id: Status.find_by_name('Flagged').id }, status_id: @active_status.id), method: :put, class: 'action') do %>
                      <span class="glyphicons flag"></span>
                    <% end unless @active_status.name == 'Flagged' %>
                    <%= link_to(ticket_path(ticket, ticket: { status_id: Status.find_by_name('Open').id }, status_id: @active_status.id), method: :put, class: 'action') do %>
                      <span class="glyphicons ok_2"></span>
                    <% end if @active_status.name == 'New' %>
                    <% if ticket.replies.visible.size > 0 %>
                    <div class="action comments-count">
                      <span class="count"><%= ticket.replies.visible.size %></span>
                       <span class="glyphicons comments"></span>
                    </div>
                    <% end %>
                </div>
                <% end %>
              </div>
          </div>
        <% end %>

    </div>

  </div>

</div>

<%= render 'change_status_form', { ticket: Ticket.new } %>

app/views/tickets/index.json.erb
    <% @tickets.each do |ticket| %>
    {
      message: <%= ticket[:message] %>,
      id: <%= ticket.id %>  
    }

    <% end %>

app/views/tickets/show.html.erb
<div class="row">
  <div class="large-9 columns">
    <div class="question">

      <% if @ticket.message.nil? %>
        (No content)
      <% else %>
      <div class="message">
        <% if @ticket.content_type == 'markdown' %>
          <% markdown = Redcarpet::Markdown.new Redcarpet::Render::HTML %>
          <% content = markdown.render(@ticket.content) %>
        <% elsif @ticket.content_type == 'text' %>
          <% content = @ticket.message.gsub("\n", '<br />') %>
        <% else %>
          <% content = @ticket.message %>
        <% end %>

        <%# only allow these tags and attributes %>
        <%= sanitize content, tags: %w(a b br code div em i img li ol p pre table td tfoot thead tr span strong ul), attributes: %w(src href) %>
      <% end %>

      </div>

    </div>

    <% if @ticket.replies.visible.size > 0 %>
      <dl class="accordion" data-accordion>

        <% count = 0 %>
        <% @ticket.replies.visible.chronologically.each do |reply| %>
          
          <dd<%= " class=answer" if reply.answer? %>>
            <div id="reply-<%=reply.id%>" class="content">
              <% if reply.content_type == 'markdown' %>
                <% markdown = Redcarpet::Markdown.new Redcarpet::Render::HTML %>
                <% content = markdown.render(reply.message) %>
              <% elsif reply.content_type == 'text' %>
                <% content = reply.message.gsub("\n", '<br />') %>
              <% else %>
                <% content = reply.message %>
              <% end %>

              <%= sanitize content, tags: %w(a b code div em i img li ol p table td tfoot thead tr span strong ul), attributes: %w(src href) %>
            </div>
            <div class="username">
              <%= reply.user.email %> 
              <div style="float:right;">
                <%= l reply.created_at, format: :short %>
                <% if @is_admin && @ticket.status.name != 'Closed' %>
                <div class="sub-action delete">
                  <%= link_to(reply_path(reply.id), method: :delete) do %>
                  <span class="glyphicons remove_2"></span>
                  <% end %>
                </div>
                <div class="sub-action approve">
                  <%= link_to(reply_approve_path(reply.id), method: :post) do %>
                  <span class="glyphicons ok_2"></span>
                  <% end %>
                </div>
                <% end %>
              </div>
            </div>
          </dd>

          <% count += 1 %>

        <% end %>

      </dl>
    <% end %>

    <%= render 'replies/form' %>
    
  </div>
  <div class="large-3 columns">
    <ul class="side-nav">
      <% if @ticket.answered? %><li>ANSWERED</li><% end %>
      <li><span class="halflings calendar"></span><%= l @ticket.created_at, format: :short %></li>
      <li><span class="halflings comments"></span><%= @ticket.replies.visible.size %> comments</li>
    </ul>

    <% if @is_admin %>
    <ul class="side-nav">
      <li class="muted"><span class="halflings phone"></span>View Phone #</li>
      <%= link_to(ticket_path(@ticket, ticket: { status_id: Status.find_by_name('Flagged').id }), status_id: @active_status.id, method: :put) do %>
      <li class="muted"><span class="halflings flag"></span>Flag Thread</li>
      <% end %>
      <%= link_to(ticket_path(@ticket, ticket: { status_id: Status.find_by_name('Deleted').id }), status_id: @active_status.id, method: :put) do %>
      <li class="muted"><span class="halflings remove"></span>Delete Thread</li>
      <% end %>
    </ul>
    <% end %>
  </div>

</div>
<%= render 'change_status_form', { ticket: @ticket } if @is_admin %>

app/views/tickets/update.js.erb
window.location.reload();