config/routes.rb
Brimir::Application.routes.draw do

  resources :replies, only: [ :create, :new, :destroy ]
  post 'replies/:id/approve' => 'replies#approve', as: 'reply_approve'

  devise_for :users
  devise_scope :user do
    post 'login' => 'sessions#create', :as => 'login'
    post 'logout' => 'sessions#destroy', :as => 'logout'
    get 'current_user' => 'sessions#show_current_user', :as => 'show_current_user'
  end

  resources :users, only: [ :edit, :update ]

  resources :tickets, only: [ :index, :show, :update, :create ]
  post 'tickets/:id/approve' => 'tickets#approve', as: 'ticket_approve'
  post 'tickets/:id/delete', :to => 'tickets#delete_ticket', as: 'delete_ticket'
  post 'tickets/:id/flag', :to => 'tickets#flag_ticket'
  post 'tickets/:id/best', :to => 'tickets#best_ticket'
  get 'all_tickets', :to => 'tickets#all'
  
  post 'replies/:id/delete', :to => 'replies#destroy_reply'
  post 'replies/:id/flag', :to => 'replies#flag_reply'

  root :to => 'tickets#index'

  resources :admins, only: [ :index]

  get '/resources' => 'pages#resources'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
      
    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : 'PiaChatto' %></title>

    <%= favicon_link_tag 'favicon.png' %>

    <%= stylesheet_link_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="contain-to-grid">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1>
              <a href="<%= root_path %>">
                <%= image_tag 'favicon.png', class: 'brand' %>
                PiaChatto
              </a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon">
            <a href="">
              <span>Menu</span>
            </a>
          </li>
        </ul>

        <section class="top-bar-section">
          
          <% if user_signed_in? %>

            <ul class="right">
              <li class="has-dropdown active">
                <a href="#"><%= current_user.email %></a>
                <ul class="dropdown">
                  <li>
                    <%= link_to 'Settings', edit_user_path(current_user) %>
                  </li>
                  <li>
                    <%= link_to 'Sign out', :destroy_user_session, method: :delete %>
                  </li>
                </ul>
              </li>
            </ul>

          <% end %>

        </section>

      </nav>
    </div>

<% if !current_page?('/users/sign_in') %>
    <div class="contain-to-grid secondary-nav">
      <nav class="top-bar" data-topbar>
        <section class="top-bar-section">
          <!-- <ul class="left">
              <li class="has-form">
                <%= form_tag tickets_path, method: :get do %>
                  <%= text_field_tag :q, params[:q], placeholder: 'Search questions' %>
                <% end %>
              </li>
          </ul>  -->
          <ul class="right">
            <% if @is_admin %>
            <li<%= ' class=active' if @active_status && @active_status.name == 'New' %>>
              <%= link_to 'Incoming', tickets_path(status_id: Status.find_by_name('New').id) %>
            </li>
            <% end %>
            <li<%= ' class=active' if @active_status && @active_status.name == 'Open' %>>
              <%= link_to 'Open', tickets_path(status_id: Status.find_by_name('Open').id) %>
            </li>
            <!-- <li<%= ' class=active' if @active_status && @active_status.name == 'Flagged' %>>
              <%= link_to 'Flagged', tickets_path(status_id: Status.find_by_name('Flagged').id) %>
            </li> -->
            <li><a href="/tickets?status_id=2">Conversations</a></li>
            <li<%= ' class=active' if @active_status && @active_status.name == 'Closed' %>>
              <%= link_to 'Archives', tickets_path(status_id: Status.find_by_name('Closed').id) %>
            </li>
            <li><a>Best</a></li>
            <li><a href="/resources">Resources</a></li>
          </ul>
        </section>
      </nav>
    </div>
<% end %>

    <%= yield %>

    <div class="reveal-modal" data-reveal>
      <article>
      </article>
      <a class="close-reveal-modal">&#215;</a>
    </div>

    <%= javascript_include_tag "application" %>

  </body>
</html>